name: Update Leaderboard

on:
  schedule:
    - cron: "*/15 * * * *"   # rulează la fiecare 15 minute
  workflow_dispatch:         # poți declanșa manual din Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run leaderboard script
        run: |
          python extract_address.py   # scriptul tău care generează leaderboard.json

      - name: Commit & Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add leaderboard.json
          git commit -m "Auto-update leaderboard.json [skip ci]" || echo "No changes to commit"
          git push
